name = "NESCGLE"
uuid = "901f7455-3196-4a43-8117-a345620cd50f"
authors = ["Ricardo Peredo-Ortiz"]
version = "0.1.0"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
